spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/fxyp?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    #    url: jdbc:mysql://localhost:3307/sg_security?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

#腾讯cos
  tengxun:
    cos:
      accessKey: AKIDqVt0rSmpb6KHyX3PWNyNa2HGzRdaMs9B
      secretKey: oMgkY6PTHpEOIxNaXFjz0mIZbOuABwRg
      bucketRegion: ap-beijing
      bucketName: fxcloud-1254493079
      path: https://fxcloud-1254493079.cos.ap-beijing.myqcloud.com
      qianzui: fxcloud



  baidu:
    ocr:
      APP_ID: 11487965
      API_KEY: 4RHdwmUxjMYSgSBcUHPhbiQm
      SECRET_KEY: mGBce6uadRUtDvH1ZtYmqDrNewltWGKW
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
  fx:
    # 文件存储位置 (0 为本地, 1 为腾讯COS对象存储 )
    fileStorageType: 0
    # 文件本地存储根路径
    fileStorageRootPath: file

# MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.fx.pan.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  supportMethodsArguments: true
#  params: count=countSql
redis:
  # 地址
  host: localhost
  # 端口，默认为6379
  port: 6379
  # 数据库索引
  database: 0
  # 密码
  password:
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
