spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/fxyp?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    #    url: jdbc:mysql://localhost:3307/sg_security?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    druid:
##      url: jdbc:mysql://localhost:3307/feixiangcloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#      url: jdbc:mysql://localhost:3307/feixiangcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password:
#      # 从库数据源
#      slave:
#        # 从数据源开关/默认关闭
#        enabled: false
#        url:
#        username:
#        password:
#      # 初始连接数
#      initialSize: 5
#      # 最小连接池数量
#      minIdle: 10
#      # 最大连接池数量
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      # 配置一个连接在池中最大生存的时间，单位是毫秒
#      maxEvictableIdleTimeMillis: 900000
#      # 配置检测连接是否有效
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      webStatFilter:
#        enabled: true
#      statViewServlet:
#        enabled: true
#        # 设置白名单，不填则允许所有访问
#        allow:
#        url-pattern: /druid/*
#        # 控制台管理用户名和密码
#        login-username: ruoyi
#        login-password: 123456
#      filter:
#        stat:
#          enabled: true
#          # 慢SQL记录
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true



  tengxun:
    cos:
      accessKey: AKIDqVt0rSmpb6KHyX3PWNyNa2HGzRdaMs9B
      secretKey: oMgkY6PTHpEOIxNaXFjz0mIZbOuABwRg
      bucketRegion: ap-beijing
      bucketName: fxcloud-1254493079
      path: https://fxcloud-1254493079.cos.ap-beijing.myqcloud.com
      qianzui: fxcloud



  baidu:
    ocr:
      APP_ID: 11487965
      API_KEY: 4RHdwmUxjMYSgSBcUHPhbiQm
      SECRET_KEY: mGBce6uadRUtDvH1ZtYmqDrNewltWGKW
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
  fx:
  # 文件存储位置 (0 为本地, 1 为腾讯COS对象存储 )
   fileStorageType: 0
  # 文件本地存储根路径
   fileStorageRootPath: file

# MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.fx.pan.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  supportMethodsArguments: true
#  params: count=countSql
redis:
  # 地址
  host: localhost
  # 端口，默认为6379
  port: 6379
  # 数据库索引
  database: 0
  # 密码
  password:
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池的最大数据库连接数
      max-active: 8
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1ms



